### ISSUE TITLE
[Deleted]

### ISSUE THREAD

**Issue by ghost** [moddingplayground/frame-fabric#4]
[Deleted]

**Comment by dvitski** [comment]
This issue appears to be exclusive to Frame functionality
I'm investigating this 👍

**Comment by dvitski** [comment]
Try Frame v0.21.1 and see if it fixes the issue
https://modrinth.com/mod/frame-api/version/0.21.1+1.19

**Comment by dvitski** [comment]
In my testing it seems to have been fixed, I'll wait for your confirmation though :)

**Comment by inflorescence91838** [comment]
It does indeed fix the issue! Thank you for your kindness.
